
### login
POST http://localhost:5001/api/auth/login
Content-Type: application/json

{
    "email": "alvindiedevelop@gmail.com",
    "password": "securepassword"
}

### Registro
POST http://localhost:5001/api/auth/register
Content-Type: application/json

{
    "name": "Alvaro Martin",
    "email": "alvind2s123ieaa@gmail.com",
    "password": "securepassword",
    "document": "PE-13-2aa17612366",
    "phone": "+50768249312353866"
}
